MakeContributions/markdown-dungeon

english/normal-dungeon/0/0-1A.md, english/normal-dungeon/0/0-1B.md, english/normal-dungeon/0/0.md, english/normal-dungeon/0/1-1A.md, english/normal-dungeon/0/1-1B.md
=> added train brain room & some emojis😁

english/normal-dungeon/1/1.md, english/normal-dungeon/1/3.md, english/normal-dungeon/1/4.md
changes include :-
1) change the wording of first ending { made it reasonable for new sequence also }
2) player now meets a sleeping dragon instead of treasure after touching the magic circle
3) if the player tries to sneak towards the dragon he/she finds it's treasure
4) now the player have 2 options 
- take the treasure  -> leads to ending 1 {dragon finds you}
- take care of the dragon first -> leads to ending 2-1C {where you try to fight dragon and dies}
=> Add sleeping dragon sequence

english/normal-dungeon/0/0.md, english/normal-dungeon/3/1-1A.md, english/normal-dungeon/3/1.md
Add new "find a way out" option and link to new floor pages"
=> add new option and linked to new floor

english/normal-dungeon/begin-journey.md, start-new-game.md
=> Added intro page

.gitignore, english/normal-dungeon/0/0-1A.md, english/normal-dungeon/0/0-1B.md, english/normal-dungeon/0/1-1A.md, english/normal-dungeon/0/1-1B.md, english/normal-dungeon/0/1-1BA.md, english/normal-dungeon/0/1-1BB.md
Please forgive me if I did too much. I was excited to contribute.
- I added two different books to read as brain training, with associated rooms.
- I corrected the spelling of "dungeon" in a few files.
- I added the emoji for meditating.
- I added ".DS_Store" to the .gitignore file, as Macs will add these files sometimes.
Thanks for reviewing!
Jeff :-)
=> added book rooms, corrected dungeon spelling

english/normal-dungeon/1/1.md, english/normal-dungeon/1/2-1C.md, english/normal-dungeon/1/3-1.md, english/normal-dungeon/2/1.md, english/normal-dungeon/3/1-1A.md
Changes include :- 
- Add link to restart the game at every ending ✅
- Add emojis to some files ✅
=> ➕ Add 🔗link to restart game

english/normal-dungeon/1/1-1.md, english/normal-dungeon/1/4.md
Let me know if I could improve on anything 😃.
=> added option to room 4 on floor 1 and new subroom (1-1)

english/normal-dungeon/0/0-1A.md, english/normal-dungeon/0/1-1B.md, english/normal-dungeon/1/2-1A.md, english/normal-dungeon/1/2-1B.md, english/normal-dungeon/1/2-1C.md, english/normal-dungeon/1/2.md, english/normal-dungeon/1/3.md, english/normal-dungeon/1/4.md, english/normal-dungeon/2/1.md, english/normal-dungeon/3/1.md, english/normal-dungeon/begin-journey.md
changes include :-
1) Add emojis wherever possible in the english version ✅
2) fix some typos ✅
=> Add 🙂emojis🙃 to english version

english/normal-dungeon/3/1.md, english/normal-dungeon/3/3.md, english/normal-dungeon/4/1-A.md, english/normal-dungeon/4/1.md, english/normal-dungeon/4/2.md, english/normal-dungeon/4/3-A.md, english/normal-dungeon/4/3-B.md, english/normal-dungeon/4/3-C.md, english/normal-dungeon/4/3.md, english/normal-dungeon/5/1-A.md, english/normal-dungeon/5/1-B.md, english/normal-dungeon/5/1.md, english/normal-dungeon/5/2.md, english/normal-dungeon/5/3.md, english/normal-dungeon/5/4.md
I had fun creating new stories based on previous stories. Also, this is my first pull request.
Main Changes : 
- Continuation of the dungeon
- Created different links and rooms
- Completed the dungeon
- Added emojis and different characters
=> Normal Dungeon Completed

english/normal-dungeon/0/0-1B.md, english/normal-dungeon/0/1-1C.md, english/normal-dungeon/0/1-1CA.md, english/normal-dungeon/0/1-1CB.md
Added a new option for training your brain by watching either a long or short instructional video.
Hope this is OK
=> added new brain training option

english/normal-dungeon/1/2-1D.md, english/normal-dungeon/1/3-3.md, english/normal-dungeon/1/3-4.md, english/normal-dungeon/1/3.md, english/normal-dungeon/1/4.md, english/normal-dungeon/4/3-B.md
Small PR to add some extra rooms.
=> Add new rooms

english/normal-dungeon/5/5.md, english/normal-dungeon/6/1.md, english/normal-dungeon/6/2.md, english/normal-dungeon/6/3.md, english/normal-dungeon/6/4.md
I've added a 6th floor in the english dungeon,branching out from the 5th room in 5th floor. There one will discover a body and hopefully solve the murder.
=> added 6th floor where one discovers a murder

english/normal-dungeon/1/1-1A.md
=> changed FOLL to FULL

english/normal-dungeon/2/3-C.md, english/normal-dungeon/2/3-D.md
To: normal dungeon
Floor: 2
I added a new sub room called 2-3D.md
Affects room 2-3C.md
=> add link from normal dungeon 2-3C to 2-3D, and add room 2-3D

english/normal-dungeon/0/0-1A.md, english/normal-dungeon/0/0-1AA.md, english/normal-dungeon/0/0-1AAA.md, english/normal-dungeon/0/0.md, english/normal-dungeon/0/1-1A.md, english/normal-dungeon/0/1-1BA.md, english/normal-dungeon/0/1-1CB.md, english/normal-dungeon/1/1.md, english/normal-dungeon/1/2-1A.md, english/normal-dungeon/1/2-1B.md, english/normal-dungeon/1/2-1C.md, english/normal-dungeon/1/3-1.md, english/normal-dungeon/1/3-2.md, english/normal-dungeon/1/3-3.md, english/normal-dungeon/1/3-4.md, english/normal-dungeon/1/3.md, english/normal-dungeon/1/4.md
I have edited files in dir 0 & 1. Please let me know if these are good and then I will continue work on the rest.
=> edited files in dir 0 and 1

english/normal-dungeon/4/1-A.md, english/normal-dungeon/4/1.md, english/normal-dungeon/4/2.md, english/normal-dungeon/4/3-A.md, english/normal-dungeon/4/3-B.md, english/normal-dungeon/4/3-C.md, english/normal-dungeon/4/3.md, english/normal-dungeon/4/4.md
Hello, 
I edited and corrected some typos in directory 4 as well. Please let me know if anything needs to be changed.
=> Edited files in directory 4

english/normal-dungeon/0/0.md, english/normal-dungeon/7/0.md, english/normal-dungeon/7/1-A.md, english/normal-dungeon/7/1-B.md, english/normal-dungeon/7/1-BA.md, english/normal-dungeon/7/1-BAB.md, english/normal-dungeon/7/1-BB.md, english/normal-dungeon/7/1-BBA.md, english/normal-dungeon/7/1-BBC.md, english/normal-dungeon/7/1-BBCA.md, english/normal-dungeon/7/1-BBCB.md, english/normal-dungeon/7/1-BC.md, english/normal-dungeon/7/1-BCA.md, english/normal-dungeon/7/1-C.md, english/normal-dungeon/7/1-CA.md, english/normal-dungeon/7/1.md, english/normal-dungeon/7/2.md
Hello friends!
Here are a few things I have done in this PR:
- Added a new floor (no. 7) to the existing `english/normal-dungeon`.
- Added 16 rooms (including sub rooms)
- Linked some of the room's options to other floors and rooms so that the game would be more _interconnected_
Please check the changes and see if this is good. By the way, I am not a good story writer, so sorry if the content is not thrilling. Feel free to edit it!
Addresses #103 
Happy Markdown Dungeon!
=> Add more floors and rooms

english/covid-19/3/3-A.md, english/covid-19/3/3-AA.md, english/covid-19/3/3-AB.md, english/covid-19/3/3.md
Improvise covid-19 dungeon expansion, fixes #103
=> expanded lamp route

english/covid-19/0/0-D.md, english/covid-19/0/0-DB.md, english/covid-19/0/0.md, english/covid-19/3/3-AA.md, english/covid-19/3/3.md
#112 fixed spelling. The route had an option to just "go into the dungeon" which didn't make sense if you were chained to a post, but another route has you break the chain after getting strong, so I don't know what we should do.
=> spell-check and re-word beginning of covid-19 dungeon for readability

portuguese/normal-dugeon/1/1-1.md, portuguese/normal-dugeon/1/1-1A.md, portuguese/normal-dugeon/1/1.md, portuguese/normal-dugeon/1/2-1A.md, portuguese/normal-dugeon/1/2-1B.md, portuguese/normal-dugeon/1/2-1C.md
Translated 5 normal-dungeon files to portuguese (or improved their translation):
- 1/1-1A.md
- 1/1.md
- 1/2-1A/md
- 1/2-1B.md
- 1/2-1C.md
Each file has been commited individually.
=> More files translated to portuguese

english/normal-dungeon/9/3-A.md, english/normal-dungeon/9/3-C.md, english/normal-dungeon/9/5-A.md, english/normal-dungeon/9/5-AB.md, english/normal-dungeon/9/5-B.md, english/normal-dungeon/9/5-C.md, english/normal-dungeon/9/5-CA.md, english/normal-dungeon/9/5-D.md, english/normal-dungeon/9/5-DA.md, english/normal-dungeon/9/6-A.md, english/normal-dungeon/9/6-B.md, english/normal-dungeon/9/6-C.md
fixes #103. 
Continued work on my dungeon
=> More paths for dungeon

english/normal-dungeon/3/2-2.md
added a 2nd line after the goblins kill you in 3/2-2. The emojis in my line render in my forked repository, but it seems like they won't in this comment for some reason.
```diff
You go to the backyard of your house 🏡 and opens the door 🚪 slightly. Suddenly, two goblins 👺👺 emerged from inside and finished you with their sharp sword ⚔️.
+ As you lay they, dying :skull: , you wonder what life would have been like if you made different decisions :thought_balloon: ...
THE END! 🎬
[🔄 Restart the game](../begin-journey.md)
```
=> added another line to 3/2-2.md

english/normal-dungeon/begin-journey.md
Replace the emoji to a weary face
=> Yawning emoji does not work on some microsoft devices

english/covid-19/begin-journey.md
Just a simple warning to users to let them know that it isn't finished.
=> Underdevelopment sign at the start of covid-19 dungeon

english/covid-19/3/3-C.md, english/covid-19/3/3.md
Added a markdown file under COVID-19 Dungeon, fixes #112
=> Expanded 'search another weapon' route

portuguese/normal-dugeon/0/0-1B.md, portuguese/normal-dugeon/0/0.md, portuguese/normal-dugeon/0/1-1C.md, portuguese/normal-dugeon/begin-journey.md, start-new-game.md
Fixed some typos and added accents to the words.
Great project and initiative! I really like open-source and would like to help translate the rest of the content
=> Fix: correcting typos

english/normal-dungeon/9/2.md, english/normal-dungeon/9/3-D.md
Cellar is currently a dead end, but creates another fork for future additional storylines.
=> Cellar option added to 2, cellar file created as 3-D

english/covid-19/0/0-BB.md, english/covid-19/0/0-BBA.md, english/covid-19/1/1-D.md, english/covid-19/1/1-DB.md
Added two new rooms, rock-paper-scissors (0/0-BBA.md) and fight virus (1/1-DB.md), along with new paths to corresponding parents (0-BB and 1-D). Please update decision_tree.png once the pull request has approved :)
=> chore(covid): added two new rooms

english/covid-19/0/0-BB.md, english/covid-19/0/0-BBA.md, english/covid-19/0/0-CA.md, english/covid-19/0/0-CC.md, english/covid-19/0/0-DA.md, english/covid-19/0/0-DB.md, english/covid-19/0/0-DD.md, english/covid-19/1/1-CB.md, english/covid-19/1/1-D.md, english/covid-19/1/1-DB.md, english/covid-19/2/2-A.md, english/covid-19/2/2.md, english/covid-19/3/3-A.md, english/covid-19/3/3-AB.md, english/covid-19/3/3-C.md, english/covid-19/3/3.md
I added emojis for a lot of rooms in the Covid dungeon. Every room all should at least have emojis by now.
=> chore(covid-19): added emojis on the rooms

english/normal-dungeon/9/0.md, english/normal-dungeon/9/1.md, english/normal-dungeon/9/2.md, english/normal-dungeon/9/3-B.md, english/normal-dungeon/9/3-C.md, english/normal-dungeon/9/3-CA.md, english/normal-dungeon/9/3-DA.md, english/normal-dungeon/9/4-A.md, english/normal-dungeon/9/4-B.md, english/normal-dungeon/9/4.md
For floor 9, I have added emojis in rooms up to room 4. Please note, **as a mac user**, there might be some of these emojis not available for you to view, which can lead to question marks like [?], so feel free to either change it or delete it. I cannot tell which emojis are not available to some users. Feel free to ask me if you need any clarification about the emoji I used.
=> docs: added emojis to normal dungeon, floor 9

english/covid-19/4/4.md
As I'm getting my first vaccine dose very soon (btw I'm from Canada), I thought of an idea about implementing a new floor that is getting vaccinated in the dungeon. While this is just an idea being planned, there are no paths linking to the new floor and the room yet. Let me know if you have any questions or don't understand about what I'm implementing. Also, the emoji I added that possibly may not be compatible on non-mac device is the shot emoji (💉).
=> chore(Covid-19): added a vaccination floor

english/normal-dungeon/4/1-A.md, english/normal-dungeon/4/1.md, english/normal-dungeon/4/2.md, english/normal-dungeon/4/3-A.md, english/normal-dungeon/4/3-B.md, english/normal-dungeon/4/3-C.md, english/normal-dungeon/4/3.md, english/normal-dungeon/4/4.md, english/normal-dungeon/5/1-A.md, english/normal-dungeon/5/1-B.md, english/normal-dungeon/5/1.md, english/normal-dungeon/5/2.md, english/normal-dungeon/5/3.md, english/normal-dungeon/5/4.md, english/normal-dungeon/5/5.md
Please check my changes. Thanks (:
=> chore: added emojis, fixed typos and grammatical errors and spaced text out

english/normal-dungeon/6/1.md, english/normal-dungeon/6/2.md, english/normal-dungeon/6/3.md, english/normal-dungeon/6/4.md, english/normal-dungeon/7/0.md, english/normal-dungeon/7/1-A.md, english/normal-dungeon/7/1-B.md, english/normal-dungeon/7/1-BA.md, english/normal-dungeon/7/1-BAB.md, english/normal-dungeon/7/1-BB.md, english/normal-dungeon/7/1-BBA.md, english/normal-dungeon/7/1-BBC.md, english/normal-dungeon/7/1-BBCA.md, english/normal-dungeon/7/1-BBCB.md, english/normal-dungeon/7/1-BC.md, english/normal-dungeon/7/1-BCA.md, english/normal-dungeon/7/1-C.md, english/normal-dungeon/7/1-CA.md, english/normal-dungeon/7/1.md, english/normal-dungeon/7/2.md
I have added some more emojis and changed visual looks. Please check my work. Thanks.
=> chore: added emojis, spaced text out and added grammar and questions

english/normal-dungeon/9/0.md, english/normal-dungeon/9/1.md, english/normal-dungeon/9/2.md, english/normal-dungeon/9/3-A.md, english/normal-dungeon/9/3-B.md, english/normal-dungeon/9/3-C.md, english/normal-dungeon/9/3-CA.md, english/normal-dungeon/9/3-CB.md, english/normal-dungeon/9/3-D.md, english/normal-dungeon/9/3-DA.md, english/normal-dungeon/9/4-A.md, english/normal-dungeon/9/4-B.md, english/normal-dungeon/9/4.md, english/normal-dungeon/9/5-A.md, english/normal-dungeon/9/5-AB.md, english/normal-dungeon/9/5-B.md, english/normal-dungeon/9/5-C.md, english/normal-dungeon/9/5-CA.md, english/normal-dungeon/9/5-D.md, english/normal-dungeon/9/5-DA.md, english/normal-dungeon/9/6-A.md, english/normal-dungeon/9/6-B.md
I have completed folder 9 of the english normal-dungeon. Thanks
=> chore: added emojis, fixed spelling errors and grammar errors, spaced text out, added bullet points and made some text italic and bold

english/time-travel/0/4.md, english/time-travel/0/5.md, english/time-travel/0/6.md
This is my first try at contributing to this project. And contributing to open source in general :)
I added some pages to the time travel dungeon area.
=> chore(time-travel): add more options

english/time-travel/0/0.md, english/time-travel/0/1.md, english/time-travel/0/2.md, english/time-travel/0/3.md, english/time-travel/0/4.md, english/time-travel/0/5.md, english/time-travel/0/6.md, english/time-travel/1/0.md, english/time-travel/1/1.md, english/time-travel/1/2.md, english/time-travel/begin-journey.md
Please review my edits. Thank you.
=> chore(time-travel): added emojis, and fix the grammar

english/covid-19/3/3-C.md, english/covid-19/3/3-CA.md
Hi all, I wanted to make a contribution. Hope this is okay.
=> chore(covid-19): added a scenario to the serum

english/covid-19/3/3-CA.md, english/covid-19/3/3-CAA.md
Hi this is my first PR. I added a new room to expand the route "🔍 Search the room again with your sensitive bat vision".
=> chore(covid-19): add a new room

english/covid-19/3/3-A.md, english/covid-19/3/3-AA.md, english/covid-19/3/3-AB.md, english/covid-19/3/3-C.md, english/covid-19/3/3-CA.md, english/covid-19/3/3-CAA.md, english/covid-19/3/3.md, english/covid-19/4/4.md
Hi, I have added some emojis, made some bold and italic text, added some questions and fixed one or two typos. Please review my code and send back any feedback if I need any. Thank you (:
=> chore: added questions, added emojis and fixed errors

english/time-travel/0/0.md, english/time-travel/0/2.md
=> docs: fix typos

english/covid-19/3/3-CA.md
Fixed typo in line 3 of room 3-CA from Waht to What
=> docs: fix typo

english/normal-dungeon/6/1.md, english/normal-dungeon/6/2.md, english/normal-dungeon/6/3.md, english/normal-dungeon/6/4.md
I fixed up the English grammar for the normal dungeon, floor 6 files 1-4.
=> docs: grammar improvments

english/covid-19/0/0-B.md
Fixed typo from excercise to exercise @UnicycleDumpTruck
=> fix: typod excercise to exercise

english/normal-dungeon/9/6-A.md, english/normal-dungeon/9/6-C.md, english/normal-dungeon/9/6-D.md, english/normal-dungeon/9/6-D1.md, english/normal-dungeon/9/6-DA.md, english/normal-dungeon/9/6-DB.md, english/normal-dungeon/9/6-E.md, english/normal-dungeon/9/6-EA.md, english/normal-dungeon/9/6-F.md
(Hi. This is my first ever pull request. Please go easy on me as this is my first time.)
Added three rooms to the corridor/dead end in the English normal-dungeon, 9th floor.
=> Added cells to corridor

english/covid-19/2/2-B.md, english/covid-19/2/2-BA.md, english/covid-19/2/2-BB.md, english/covid-19/2/2-BBC.md, english/covid-19/2/2.md
hi i have added some  story  in Covid-19 in 2 Phase
=> chore(COVID-19): add new story

README.md
=> docs: proofread the readme

src/components/copyright.jsx
=> fix: footer reference

english/covid-19/0/0-CD.md
=> chore(COVID-19): add end path

english/covid-19/0/0-C.md
=> chore(COVID-19): add new hope option

spanish/normal-dungeon/0/0-1A.md, spanish/normal-dungeon/0/0-1AA.md, spanish/normal-dungeon/0/0-1AAA.md, spanish/normal-dungeon/0/0-1B.md, spanish/normal-dungeon/0/0.md, spanish/normal-dungeon/0/1-1A.md, spanish/normal-dungeon/0/1-1B.md, spanish/normal-dungeon/0/1-1BA.md, spanish/normal-dungeon/0/1-1BB.md, spanish/normal-dungeon/0/1-1BC.md, spanish/normal-dungeon/0/1-1C.md, spanish/normal-dungeon/0/1-1CA.md, spanish/normal-dungeon/0/1-1CB.md, spanish/normal-dungeon/begin-journey.md
Fix spelling for all files inside the `/spanish/normal-dungeon/0` folder and `begin-journey.md` file.
=> fix(spanish): normal dungeon spelling problems

english/time-travel/2/0.md, english/time-travel/2/1.md, english/time-travel/2/2-A.md, english/time-travel/2/2-B.md, english/time-travel/2/2.md, english/time-travel/2/3-A.md, english/time-travel/2/3-B.md, english/time-travel/2/3.md, english/time-travel/begin-journey.md
Addresses issue #128. Please review this pull request. Thank you.
=> enh(time-travel): add more floors and rooms

english/normal-dungeon/5/1.md
=> chore(normal-dungeon): change option title

src/pages/404.jsx
This was my first contribution :)
=> chore: change not found sentence

english/time-travel/0/8/8-2AE.md, english/time-travel/0/8/8-2AEA.md
Hi, the markdown link was not pointing to the correct page. I have also changed the events of room 8-2AEA.
=> fix(time-travel): broken markdown link

.github/workflows/codespell.yml, translations/README.fr.md, translations/README.md
Hi @ming-tsai, Thanks for responding to my Pull request: #229 and thanks also for your suggestions to use the correct flag for french.
I think I accidentally forced mergin and deleted some file.
But after doing some modification and following your suggestion, I made this change.
Can you review this and tell me if something wrong with this PR please?
Pull request: #229
=> docs(translation): add french README.md
